-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- TODO: manual review: desktop_launch_prefix = "uwsm app"

-- TODO: manual review: desktop_icons = true
