-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

hl.workspace_rule({
    workspace = 1,
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = 2,
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = 3,
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = 4,
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = 5,
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = 6,
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = 7,
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = 8,
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = 9,
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = 10,
    monitor = "eDP-1",
})

hl.window_rule({
    name  = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

-- Hyprland-run windowrule

hl.window_rule({
    name  = "move-hyprland-run",
    match = {
        class = "hyprland-run",
    },
    move = { 20, "monitor_h-120" },
    float = true,
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})
