-- Cyberpunk Neovim theme
-- Generated from hypranime theme.toml

local M = {}

M.name = "cyberpunk"
M.display_name = "Cyberpunk 2077"

M.colors = {
    base00 = "#0d0d0d",
    base01 = "#1a1a1a",
    base02 = "#2a2a2a",
    base03 = "#3a3a3a",
    base04 = "#cccccc",
    base05 = "#ffffff",
    base06 = "#ffffff",
    base07 = "#ffffff",
    base08 = "#ff6b6b",
    base09 = "#ff9f43",
    base0A = "#ffe66d",
    base0B = "#69db7c",
    base0C = "#5fe4ff",
    base0D = "#74b9ff",
    base0E = "#a29bfe",
    base0F = "#ff7675",
}

M.groups = {
    -- Base
    Normal = { fg = M.colors.base05, bg = M.colors.base00 },
    NormalNC = { fg = M.colors.base05, bg = M.colors.base00 },
    NormalFloat = { fg = M.colors.base05, bg = M.colors.base01 },
    FloatBorder = { fg = M.colors.base0D, bg = M.colors.base01 },
    CursorLine = { bg = M.colors.base01 },
    CursorColumn = { bg = M.colors.base01 },
    Cursor = { fg = M.colors.base00, bg = M.colors.base0D },
    CursorIM = { fg = M.colors.base00, bg = M.colors.base0D },
    LineNr = { fg = M.colors.base03 },
    CursorLineNr = { fg = M.colors.base0D, bold = true },
    SignColumn = { fg = M.colors.base03, bg = M.colors.base00 },
    VertSplit = { fg = M.colors.base03 },
    WinSeparator = { fg = M.colors.base03 },
    Folded = { fg = M.colors.base04, bg = M.colors.base01 },
    FoldColumn = { fg = M.colors.base03, bg = M.colors.base00 },
    ColorColumn = { bg = M.colors.base01 },
    Conceal = { fg = M.colors.base04 },
    Visual = { bg = M.colors.base02 },
    VisualNOS = { bg = M.colors.base02 },
    Search = { fg = M.colors.base00, bg = M.colors.base0A },
    IncSearch = { fg = M.colors.base00, bg = M.colors.base0D },
    CurSearch = { fg = M.colors.base00, bg = M.colors.base0D },
    MatchParen = { fg = M.colors.base0D, bold = true, underline = true },
    SpecialKey = { fg = M.colors.base03 },
    NonText = { fg = M.colors.base03 },
    Whitespace = { fg = M.colors.base03 },
    EndOfBuffer = { fg = M.colors.base00 },

    -- Syntax
    Comment = { fg = M.colors.base03, italic = true },
    Constant = { fg = M.colors.base09 },
    String = { fg = M.colors.base0B },
    Character = { fg = M.colors.base0B },
    Number = { fg = M.colors.base09 },
    Boolean = { fg = M.colors.base09 },
    Float = { fg = M.colors.base09 },
    Identifier = { fg = M.colors.base08 },
    Function = { fg = M.colors.base0D },
    Statement = { fg = M.colors.base0E },
    Conditional = { fg = M.colors.base0E },
    Repeat = { fg = M.colors.base0E },
    Label = { fg = M.colors.base0E },
    Operator = { fg = M.colors.base05 },
    Keyword = { fg = M.colors.base0E, italic = true },
    Exception = { fg = M.colors.base08 },
    PreProc = { fg = M.colors.base0A },
    Include = { fg = M.colors.base0A },
    Define = { fg = M.colors.base0A },
    Macro = { fg = M.colors.base0A },
    PreCondit = { fg = M.colors.base0A },
    Type = { fg = M.colors.base0A },
    StorageClass = { fg = M.colors.base0A },
    Structure = { fg = M.colors.base0A },
    Typedef = { fg = M.colors.base0A },
    Special = { fg = M.colors.base0C },
    SpecialChar = { fg = M.colors.base0C },
    Tag = { fg = M.colors.base0D },
    Delimiter = { fg = M.colors.base05 },
    SpecialComment = { fg = M.colors.base03 },
    Debug = { fg = M.colors.base08 },
    Underlined = { underline = true },
    Ignore = { fg = M.colors.base03 },
    Error = { fg = M.colors.base08, bold = true },
    Todo = { fg = M.colors.base0A, bold = true },

    -- UI
    Pmenu = { fg = M.colors.base05, bg = M.colors.base01 },
    PmenuSel = { fg = M.colors.base00, bg = M.colors.base0D },
    PmenuSbar = { bg = M.colors.base02 },
    PmenuThumb = { bg = M.colors.base0D },
    TabLine = { fg = M.colors.base04, bg = M.colors.base01 },
    TabLineFill = { bg = M.colors.base01 },
    TabLineSel = { fg = M.colors.base00, bg = M.colors.base0D, bold = true },
    StatusLine = { fg = M.colors.base05, bg = M.colors.base01 },
    StatusLineNC = { fg = M.colors.base04, bg = M.colors.base01 },
    WildMenu = { fg = M.colors.base00, bg = M.colors.base0D },
    ModeMsg = { fg = M.colors.base0B },
    MsgArea = { fg = M.colors.base05 },
    MsgSeparator = { fg = M.colors.base03 },
    MoreMsg = { fg = M.colors.base0B },
    Question = { fg = M.colors.base0D },
    WarningMsg = { fg = M.colors.base0A },
    ErrorMsg = { fg = M.colors.base08 },
    Title = { fg = M.colors.base0D, bold = true },
    Directory = { fg = M.colors.base0D },
    DiffAdd = { fg = M.colors.base0B, bg = M.colors.base01 },
    DiffChange = { fg = M.colors.base0A, bg = M.colors.base01 },
    DiffDelete = { fg = M.colors.base08, bg = M.colors.base01 },
    DiffText = { fg = M.colors.base0D, bg = M.colors.base02 },

    -- LSP
    DiagnosticError = { fg = M.colors.base08 },
    DiagnosticWarn = { fg = M.colors.base0A },
    DiagnosticInfo = { fg = M.colors.base0D },
    DiagnosticHint = { fg = M.colors.base0C },
    DiagnosticVirtualTextError = { fg = M.colors.base08, bg = M.colors.base01 },
    DiagnosticVirtualTextWarn = { fg = M.colors.base0A, bg = M.colors.base01 },
    DiagnosticVirtualTextInfo = { fg = M.colors.base0D, bg = M.colors.base01 },
    DiagnosticVirtualTextHint = { fg = M.colors.base0C, bg = M.colors.base01 },
    DiagnosticUnderlineError = { undercurl = true, sp = M.colors.base08 },
    DiagnosticUnderlineWarn = { undercurl = true, sp = M.colors.base0A },
    DiagnosticUnderlineInfo = { undercurl = true, sp = M.colors.base0D },
    DiagnosticUnderlineHint = { undercurl = true, sp = M.colors.base0C },
    LspReferenceText = { bg = M.colors.base02 },
    LspReferenceRead = { bg = M.colors.base02 },
    LspReferenceWrite = { bg = M.colors.base02 },
    LspCodeLens = { fg = M.colors.base03 },
    LspCodeLensSeparator = { fg = M.colors.base03 },

    -- Treesitter
    ["@variable"] = { fg = M.colors.base05 },
    ["@variable.builtin"] = { fg = M.colors.base08 },
    ["@variable.parameter"] = { fg = M.colors.base08 },
    ["@variable.member"] = { fg = M.colors.base05 },
    ["@constant"] = { fg = M.colors.base09 },
    ["@constant.builtin"] = { fg = M.colors.base09 },
    ["@constant.macro"] = { fg = M.colors.base09 },
    ["@module"] = { fg = M.colors.base0A },
    ["@label"] = { fg = M.colors.base0A },
    ["@string"] = { fg = M.colors.base0B },
    ["@string.escape"] = { fg = M.colors.base0C },
    ["@character"] = { fg = M.colors.base0B },
    ["@number"] = { fg = M.colors.base09 },
    ["@boolean"] = { fg = M.colors.base09 },
    ["@type"] = { fg = M.colors.base0A },
    ["@type.builtin"] = { fg = M.colors.base0A },
    ["@attribute"] = { fg = M.colors.base0A },
    ["@property"] = { fg = M.colors.base05 },
    ["@function"] = { fg = M.colors.base0D },
    ["@function.builtin"] = { fg = M.colors.base0D },
    ["@function.macro"] = { fg = M.colors.base0D },
    ["@constructor"] = { fg = M.colors.base0D },
    ["@keyword"] = { fg = M.colors.base0E, italic = true },
    ["@keyword.function"] = { fg = M.colors.base0E, italic = true },
    ["@keyword.operator"] = { fg = M.colors.base0E },
    ["@keyword.return"] = { fg = M.colors.base0E, italic = true },
    ["@conditional"] = { fg = M.colors.base0E },
    ["@repeat"] = { fg = M.colors.base0E },
    ["@operator"] = { fg = M.colors.base05 },
    ["@punctuation"] = { fg = M.colors.base05 },
    ["@comment"] = { fg = M.colors.base03, italic = true },
    ["@tag"] = { fg = M.colors.base0D },
    ["@tag.attribute"] = { fg = M.colors.base0A },
    ["@tag.delimiter"] = { fg = M.colors.base05 },

    -- Plugins
    TelescopeNormal = { fg = M.colors.base05, bg = M.colors.base01 },
    TelescopeBorder = { fg = M.colors.base0D, bg = M.colors.base01 },
    TelescopePromptBorder = { fg = M.colors.base0D, bg = M.colors.base01 },
    TelescopeResultsBorder = { fg = M.colors.base0D, bg = M.colors.base01 },
    TelescopePreviewBorder = { fg = M.colors.base0D, bg = M.colors.base01 },
    TelescopeSelection = { fg = M.colors.base00, bg = M.colors.base0D },
    TelescopeSelectionCaret = { fg = M.colors.base0D, bg = M.colors.base0D },
    TelescopeMultiSelection = { fg = M.colors.base0C, bg = M.colors.base02 },
    TelescopeMatching = { fg = M.colors.base0D, bold = true },
    TelescopePromptPrefix = { fg = M.colors.base0D },

    NvimTreeNormal = { fg = M.colors.base05, bg = M.colors.base00 },
    NvimTreeRootFolder = { fg = M.colors.base0D, bold = true },
    NvimTreeGitDirty = { fg = M.colors.base0A },
    NvimTreeGitNew = { fg = M.colors.base0B },
    NvimTreeGitDeleted = { fg = M.colors.base08 },
    NvimTreeSpecialFile = { fg = M.colors.base0E, underline = true },
    NvimTreeIndentMarker = { fg = M.colors.base03 },
    NvimTreeFolderIcon = { fg = M.colors.base0D },
    NvimTreeFolderName = { fg = M.colors.base05 },
    NvimTreeOpenedFolderName = { fg = M.colors.base0D, bold = true },
    NvimTreeEmptyFolderName = { fg = M.colors.base04 },
    NvimTreeSymlink = { fg = M.colors.base0C },
    NvimTreeExecFile = { fg = M.colors.base0B, bold = true },

    WhichKey = { fg = M.colors.base0D },
    WhichKeyGroup = { fg = M.colors.base0A },
    WhichKeyDesc = { fg = M.colors.base05 },
    WhichKeySeperator = { fg = M.colors.base03 },
    WhichKeyFloat = { bg = M.colors.base01 },
    WhichKeyValue = { fg = M.colors.base04 },

    GitSignsAdd = { fg = M.colors.base0B },
    GitSignsChange = { fg = M.colors.base0A },
    GitSignsDelete = { fg = M.colors.base08 },

    IndentBlanklineChar = { fg = M.colors.base02 },
    IndentBlanklineContextChar = { fg = M.colors.base0D },

    BufferLineFill = { bg = M.colors.base01 },
    BufferLineBackground = { fg = M.colors.base04, bg = M.colors.base01 },
    BufferLineBufferVisible = { fg = M.colors.base05, bg = M.colors.base01 },
    BufferLineBufferSelected = { fg = M.colors.base00, bg = M.colors.base0D, bold = true },
    BufferLineSeparator = { fg = M.colors.base03, bg = M.colors.base01 },
    BufferLineSeparatorVisible = { fg = M.colors.base03, bg = M.colors.base01 },
    BufferLineSeparatorSelected = { fg = M.colors.base0D, bg = M.colors.base0D },
    BufferLineIndicatorSelected = { fg = M.colors.base0D, bg = M.colors.base0D },
    BufferLineModified = { fg = M.colors.base0A, bg = M.colors.base01 },
    BufferLineModifiedVisible = { fg = M.colors.base0A, bg = M.colors.base01 },
    BufferLineModifiedSelected = { fg = M.colors.base0A, bg = M.colors.base0D },

    CmpItemAbbr = { fg = M.colors.base05 },
    CmpItemAbbrDeprecated = { fg = M.colors.base03, strikethrough = true },
    CmpItemAbbrMatch = { fg = M.colors.base0D, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = M.colors.base0D, bold = true },
    CmpItemKind = { fg = M.colors.base0A },
    CmpItemMenu = { fg = M.colors.base04 },
    CmpDocumentation = { fg = M.colors.base05, bg = M.colors.base01 },
    CmpDocumentationBorder = { fg = M.colors.base0D, bg = M.colors.base01 },

    NotifyBackground = { bg = M.colors.base00 },
    NotifyERRORBorder = { fg = M.colors.base08 },
    NotifyWARNBorder = { fg = M.colors.base0A },
    NotifyINFOBorder = { fg = M.colors.base0D },
    NotifyDEBUGBorder = { fg = M.colors.base03 },
    NotifyTRACEBorder = { fg = M.colors.base0E },
}

function M.setup()
    vim.cmd("hi clear")
    if vim.fn.exists("syntax_on") then
        vim.cmd("syntax reset")
    end
    vim.o.termguicolors = true
    vim.g.colors_name = M.name

    for group, opts in pairs(M.groups) do
        vim.api.nvim_set_hl(0, group, opts)
    end
end

return M