-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--################

--## AUTOSTART ###

--################


--exec-once = wl-paste --watch cliphist store



--exec-once = eww open clock --screen 1 & eww open system --screen 1 & eww open toji --screen 1 & eww open wakatime --screen 1


-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("swww-daemon & swww img ~/.wallpapers/toji_red.png --transition-type none")
    hl.exec_cmd("waybar & wl-paste --watch cliphist store & eww open clock --screen 0 & eww open matrix --screen 0 & eww open toji --screen 0 & eww open wakatime --screen 0")
    hl.exec_cmd("hyprwave")
end)
