-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- source = ~/.config/hypr/monitors.conf -> requires manual conversion
-- local monitors = require("monitors")
-- TODO: convert ~/.config/hypr/monitors.conf to .lua and use require()

-- source = ~/.config/hypr/variables.conf -> requires manual conversion
-- local variables = require("variables")
-- TODO: convert ~/.config/hypr/variables.conf to .lua and use require()

-- source = ~/.config/hypr/autostart.conf -> requires manual conversion
-- local autostart = require("autostart")
-- TODO: convert ~/.config/hypr/autostart.conf to .lua and use require()

-- source = ~/.config/hypr/permissions.conf -> requires manual conversion
-- local permissions = require("permissions")
-- TODO: convert ~/.config/hypr/permissions.conf to .lua and use require()

-- source = ~/.config/hypr/appearences.conf -> requires manual conversion
-- local appearences = require("appearences")
-- TODO: convert ~/.config/hypr/appearences.conf to .lua and use require()

-- source = ~/.config/hypr/input.conf -> requires manual conversion
-- local input = require("input")
-- TODO: convert ~/.config/hypr/input.conf to .lua and use require()

-- source = ~/.config/hypr/keybinds.conf -> requires manual conversion
-- local keybinds = require("keybinds")
-- TODO: convert ~/.config/hypr/keybinds.conf to .lua and use require()

-- source = ~/.config/hypr/workspaces.conf -> requires manual conversion
-- local workspaces = require("workspaces")
-- TODO: convert ~/.config/hypr/workspaces.conf to .lua and use require()

require("monitors")
require("variables")
require("autostart")
require("permissions")
require("appearences")
require("input")
require("keybinds")
require("workspaces")
