-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--##################

--## MY PROGRAMS ###

--##################

local terminal = "kitty"

local fileManager = "nautilus"

local menu = "hyprlauncher"

--############################

--## ENVIRONMENT VARIABLES ###

--############################

hl.env("XCURSOR_SIZE", 26)

hl.env("HYPRCURSOR_SIZE", 26)
